name: Vault
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  vault:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Vault secrets
        run: echo "Fetching secrets for ${{ inputs.environment }}"
