name: CI + CD
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    uses: ucode/ci-cd/.github/workflows/components/build.yml@main
    with:
      node-version: ${{ inputs.node-version }}

  deploy:
    needs: [build]
    uses: ucode/ci-cd/.github/workflows/components/deploy.yml@main
    with:
      environment: ${{ inputs.environment }}
